[package]
name = "valence_stresser"
description = "A stresser for Valence Minecraft server framework development purposes."
authors = ["qualterz <qualterz@tutamail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
valence_protocol = { version = "0.1.0", path = "../valence_protocol" }
